name: it-tools
services:
  it-tools:
    image: ghcr.io/corentinth/it-tools:${ITTOOLS_VERSION}
    restart: unless-stopped
    ports:
      - "${ITTOOLS_PORT}:80"
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=it-tools
      - tsdproxy.ephemeral=true
      - tsdproxy.container_port=80
