name: grafana
networks:
  grafana-bridge:
    driver: bridge
services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    restart: unless-stopped
    user: 1000:1000
    ports:
      - "${GRAFANA_PORT}:3000"
    networks:
      - grafana-bridge
    volumes:
      - "${GRAFANA_CONFIG_PATH}:/var/lib/grafana"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=grafana
      - tsdproxy.ephemeral=true
      - tsdproxy.container_port=3000
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    restart: unless-stopped
    user: 1000:1000
    ports:
      - "9090:9090"
    networks:
      - grafana-bridge
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - "${PROMETHEUS_DATA_PATH}:/prometheus"
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.path=/prometheus
  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION}
    restart: unless-stopped
    networks:
      - grafana-bridge
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)