name: immich
configs:
  serve.json:
    content: |
      {"TCP":{"443":{"HTTPS":true}},"Web":{"$${TS_CERT_DOMAIN}:443":{"Handlers":{"/":{"Proxy":"http://127.0.0.1:${TAILSCALE_PORT}"}}}},"AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}
services:
  immich:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    restart: unless-stopped
    user: '1000:1000'
    depends_on:
      - redis
      - postgres
    environment:
      UMASK: '002'
      UPLOAD_LOCATION: /mnt/hdd/data/photos
      DB_DATA_LOCATION: /var/lib/postgresql/data
      DB_HOSTNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
    volumes:
      - "${IMMICH_CONFIG_PATH}:/data"
      - /etc/localtime:/etc/localtime:ro
  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_ML_VERSION}
    restart: unless-stopped
    volumes:
      - "${IMMICH_CACHE_PATH}:/cache"
  postgres:
    image: ghcr.io/immich-app/postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: "--data-checksums"
      DB_STORAGE_TYPE: HDD
    shm_size: 128mb
    volumes:
      - "${POSTGRES_DATA_PATH}:/var/lib/postgresql/data"
  redis:
    image: docker.io/valkey/valkey:${REDIS_VERSION}
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
  tailscale:
    image: tailscale/tailscale:${TAILSCALE_VERSION}
    restart: unless-stopped
    hostname: ${TAILSCALE_HOSTNAME}
    ports:
      - "${IMMICH_PORT}:2283"
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_USERSPACE=false
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    configs:
      - source: serve.json
        target: /config/serve.json
    volumes:
      - ${TAILSCALE_STATE_PATH}:/var/lib/tailscale
    
