name: immich
configs:
  serve.json:
    content: |
      {"TCP":{"443":{"HTTPS":true}},"Web":{"$${TS_CERT_DOMAIN}:443":{"Handlers":{"/":{"Proxy":"http://127.0.0.1:${TAILSCALE_PORT}"}}}},"AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}
services:
  immich:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    restart: unless-stopped
    user: "${IMMICH_USER}"
    depends_on:
      - redis
      - postgres
    environment:
      UMASK: "002"
      DB_HOSTNAME: postgres
      DB_DATABASE_NAME: ${POSTGRES_DATABASE_NAME}
      DB_USERNAME: ${POSTGRES_USERNAME}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      IMMICH_WORKERS: 1
    volumes:
      - "${IMMICH_MEDIA_PATH}:/data"
      - /etc/localtime:/etc/localtime:ro
    network_mode: service:tailscale
    cpus: 2.0
    mem_limit: 4g
  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_ML_VERSION}
    restart: unless-stopped
    volumes:
      - "${IMMICH_CACHE_PATH}:/cache"
    environment:
      MACHINE_LEARNING_WORKERS: 1
    cpus: 1.5
    mem_limit: 3g
  postgres:
    image: ghcr.io/immich-app/postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: ${POSTGRES_STORAGE_TYPE}
    shm_size: 128mb
    volumes:
      - "${POSTGRES_DATA_PATH}:/var/lib/postgresql/data"
    healthcheck:
      disable: false
  redis:
    image: docker.io/valkey/valkey:${REDIS_VERSION}
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
  tailscale:
    image: tailscale/tailscale:${TAILSCALE_VERSION}
    restart: unless-stopped
    hostname: ${TAILSCALE_MACHINE_NAME}
    ports:
      - "${IMMICH_PORT}:2283"
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_USERSPACE=false
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    configs:
      - source: serve.json
        target: /config/serve.json
    volumes:
      - ${TAILSCALE_STATE_PATH}:/var/lib/tailscale