name: metube
services:
  metube:
    image: ghcr.io/alexta69/metube:${METUBE_VERSION}
    restart: unless-stopped
    user: '1000:1000'
    environment:
      UMASK: '002'
    ports:
      - "${METUBE_PORT}:8081"
    volumes:
      - "${METUBE_DOWNLOADS_PATH}:/downloads"
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=metube
      - tsdproxy.ephemeral=true
      - tsdproxy.container_port=8081
