name: copyparty
services:
  copyparty:
    image: copyparty/ac:${COPYPARTY_VERSION}
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - ${COPYPARTY_PORT}:3923
    volumes:
      - ./:/cfg:z
      - "${COPYPARTY_MEDIA_PATH}:/w:z"
    environment:
      LD_PRELOAD: /usr/lib/libmimalloc-secure.so.NOPE
      PYTHONUNBUFFERED: 1
    stop_grace_period: 15s
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:3923/?reset=/._"]
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 15s