name: searxng
services:
  searxng:
    image: docker.io/searxng/searxng:${SEARXNG_VERSION}
    restart: unless-stopped
    environment:
      SEARXNG_BASE_URL: ${SEARXNG_BASE_URL}
    ports:
      - "${SEARXNG_PORT}:8080"
    volumes:
      - "${SEARXNG_CONFIG_PATH}:/etc/searxng:rw"
      - searxng-data:/var/cache/searxng:rw
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=searxng
      - tsdproxy.ephemeral=true
      - tsdproxy.container_port=8080
  redis:
    image: docker.io/valkey/valkey:${VALKEY_VERSION}
    restart: unless-stopped
    command: valkey-server --save 30 1 --loglevel warning
    volumes:
      - valkey-data:/data
volumes:
  searxng-data:
  valkey-data:
