name: searxng
configs:
  serve.json:
    content: |
      {"TCP":{"443":{"HTTPS":true}},"Web":{"$${TS_CERT_DOMAIN}:443":{"Handlers":{"/":{"Proxy":"http://127.0.0.1:${TAILSCALE_PORT}"}}}},"AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}
services:
  searxng:
    image: docker.io/searxng/searxng:${SEARXNG_VERSION}
    restart: unless-stopped
    environment:
      SEARXNG_BASE_URL: ${SEARXNG_BASE_URL}
    volumes:
      - "${SEARXNG_CONFIG_PATH}:/etc/searxng:rw"
      - searxng-data:/var/cache/searxng:rw
    network_mode: service:tailscale
  redis:
    image: docker.io/valkey/valkey:${VALKEY_VERSION}
    restart: unless-stopped
    command: valkey-server --save 30 1 --loglevel warning
    volumes:
      - valkey-data:/data    
  tailscale:
    image: tailscale/tailscale:${TAILSCALE_VERSION}
    restart: unless-stopped
    hostname: ${TAILSCALE_HOSTNAME}
    ports:
      - "${SEARXNG_PORT}:8080"
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_USERSPACE=false
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    configs:
      - source: serve.json
        target: /config/serve.json
    volumes:
      - ${TAILSCALE_STATE_PATH}:/var/lib/tailscale
volumes:
  searxng-data:
  valkey-data:
